/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ui.internal.GuixDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GuixDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GuixDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GuixDslActivator.getInstance().getInjector(GuixDslActivator.ORG_GUIXDSL);
	}
	
}
