/*
* generated by Xtext
*/
package org.ui.contentassist;

import org.ui.contentassist.AbstractGuixDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GuixDslProposalProvider extends AbstractGuixDslProposalProvider {

}
