/*
* generated by Xtext
*/
package org.guixdsl.ui.contentassist;

import org.guixdsl.ui.contentassist.AbstractGuixdslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GuixdslProposalProvider extends AbstractGuixdslProposalProvider {

}
