/*
 * generated by Xtext
 */
package org.guixdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GuixdslUiModule extends org.guixdsl.ui.AbstractGuixdslUiModule {
	public GuixdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
