/*
* generated by Xtext
*/
package org.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.services.GuixDslGrammarAccess;

public class GuixDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GuixDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parser.antlr.internal.InternalGuixDslParser createParser(XtextTokenStream stream) {
		return new org.parser.antlr.internal.InternalGuixDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DslModel";
	}
	
	public GuixDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GuixDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
