/*
* generated by Xtext
*/
package org.guixdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.guixdsl.services.GuixdslGrammarAccess;

public class GuixdslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GuixdslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.guixdsl.parser.antlr.internal.InternalGuixdslParser createParser(XtextTokenStream stream) {
		return new org.guixdsl.parser.antlr.internal.InternalGuixdslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DslModel";
	}
	
	public GuixdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GuixdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
