/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GuixDslUiModule extends org.ui.AbstractGuixDslUiModule {
	public GuixDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
