/*
 * generated by Xtext
 */
package org.guixdsl;

import org.eclipse.xtext.generator.IGenerator;
import org.guixdsl.generator.GuixdslGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GuixdslRuntimeModule extends org.guixdsl.AbstractGuixdslRuntimeModule {
    /**
     * Avoid using the default org.eclipse.xtext.xbase.compiler.JvmModelGenerator
     * when using xbase.
     * @see org.guixdsl.AbstractGuixdslRuntimeModule#bindIGenerator()
     */
    @Override
    public Class<? extends IGenerator> bindIGenerator() {
        return GuixdslGenerator.class;
    }

}
