/*
* generated by Xtext
*/
package org.guixdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GuixdslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.guixdsl.ui.internal.GuixdslActivator.getInstance().getInjector("org.guixdsl.Guixdsl");
	}
	
}
