/*
 * generated by Xtext
 */
package org;

import org.eclipse.xtext.generator.IGenerator;
import org.generator.GuixDslGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GuixDslRuntimeModule extends org.AbstractGuixDslRuntimeModule {

    /**
     * Avoids to use the default org.eclipse.xtext.xbase.compiler.JvmModelGenerator
     * when using xbase.
     * @see org.xtext.example.helloxbase.AbstractHelloXbaseRuntimeModule#bindIGenerator()
     */
    @Override
    public Class<? extends IGenerator> bindIGenerator() {
        return GuixDslGenerator.class;
    }
    
}
